// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEPhb6mxTTOdD53GqvQP9GoLcy_YBslFY',
    appId: '1:144054415332:web:cfd36d2c9b76c5987f61f1',
    messagingSenderId: '144054415332',
    projectId: 'nextjs-ga-web',
    authDomain: 'nextjs-ga-web.firebaseapp.com',
    storageBucket: 'nextjs-ga-web.appspot.com',
    measurementId: 'G-ST54088R0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCqubvmLxey3JueOFDeF9fMw1wMYZwEto',
    appId: '1:144054415332:android:521ee5c695c6b21d7f61f1',
    messagingSenderId: '144054415332',
    projectId: 'nextjs-ga-web',
    storageBucket: 'nextjs-ga-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJs_gjIZyaku_lTIU-kNv0zKN1V1QYDTM',
    appId: '1:144054415332:ios:9902245ddad625157f61f1',
    messagingSenderId: '144054415332',
    projectId: 'nextjs-ga-web',
    storageBucket: 'nextjs-ga-web.appspot.com',
    iosClientId: '144054415332-3r6fjl145j4i1l2eq7hi8hou99hismiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.trialga',
  );
}
